version: '3.1'

services:

  web-server:
    image: php:5.4.34-apache
    restart: always
    container_name: loft-sv-old    
    ports:
      - 8121:80
    volumes:
      - ./dist/:/var/www/html
    
